server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  max_connections: 10000
  keep_alive: true
  keep_alive_period: 60s

database:
  connection_string: "user/password@localhost:1521/ORCL"
  max_open_conns: 50
  max_idle_conns: 25
  conn_max_lifetime: 5m
  poll_interval: 100ms
  lock_timeout: 5s
  table_name: "unsend_data"
  response_table: "api_responses"

api:
  base_url: "https://api.example.com"
  timeout: 30s
  max_retries: 3
  retry_delay: 1s
  max_idle_conns: 100
  max_idle_conns_per_host: 10
  tls_insecure_skip: false

worker:
  pool_size: 100
  queue_size: 1000
  process_timeout: 60s

logging:
  level: "info"
  format: "json"
  output_path: "stdout"
